## default config

plugins = ["ssh", "shell"]
default_build_path = "/tmp/"

[db]
type = "sqlite3"
## only for sqlite3
path = "scheduler.db"

host = "localhost"
port = 5434
name = "postgres"
password = "postgres"
user = "postgres"

[admin]
email = "admin@localhost.com"
password = "123456"

